/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ImmersiveRouteImport } from './routes/_immersive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWordRouteImport } from './routes/w.$word'
import { Route as ApiWritingCoachRouteImport } from './routes/api.writing-coach'
import { Route as ApiWordRouteImport } from './routes/api.word'
import { Route as ApiSentenceRouteImport } from './routes/api.sentence'
import { Route as ProtectedWritingCoachRouteImport } from './routes/_protected.writing-coach'
import { Route as ProtectedVocabularyRouteImport } from './routes/_protected.vocabulary'
import { Route as ProtectedTrRouteImport } from './routes/_protected.tr'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected.api-keys'
import { Route as ImmersiveWarmupRouteImport } from './routes/_immersive.warmup'
import { Route as ProtectedVocabularyIndexRouteImport } from './routes/_protected.vocabulary.index'
import { Route as AudioWWordRouteImport } from './routes/audio.w.$word'
import { Route as ProtectedVocabularyImportRouteImport } from './routes/_protected.vocabulary.import'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersiveRoute = ImmersiveRouteImport.update({
  id: '/_immersive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWordRoute = WWordRouteImport.update({
  id: '/w/$word',
  path: '/w/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWritingCoachRoute = ApiWritingCoachRouteImport.update({
  id: '/api/writing-coach',
  path: '/api/writing-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordRoute = ApiWordRouteImport.update({
  id: '/api/word',
  path: '/api/word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentenceRoute = ApiSentenceRouteImport.update({
  id: '/api/sentence',
  path: '/api/sentence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWritingCoachRoute = ProtectedWritingCoachRouteImport.update({
  id: '/writing-coach',
  path: '/writing-coach',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVocabularyRoute = ProtectedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTrRoute = ProtectedTrRouteImport.update({
  id: '/tr',
  path: '/tr',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ImmersiveWarmupRoute = ImmersiveWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => ImmersiveRoute,
} as any)
const ProtectedVocabularyIndexRoute =
  ProtectedVocabularyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedVocabularyRoute,
  } as any)
const AudioWWordRoute = AudioWWordRouteImport.update({
  id: '/audio/w/$word',
  path: '/audio/w/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedVocabularyImportRoute =
  ProtectedVocabularyImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ProtectedVocabularyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/warmup': typeof ImmersiveWarmupRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/tr': typeof ProtectedTrRoute
  '/vocabulary': typeof ProtectedVocabularyRouteWithChildren
  '/writing-coach': typeof ProtectedWritingCoachRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/word': typeof ApiWordRoute
  '/api/writing-coach': typeof ApiWritingCoachRoute
  '/w/$word': typeof WWordRoute
  '/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/vocabulary/': typeof ProtectedVocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/warmup': typeof ImmersiveWarmupRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/tr': typeof ProtectedTrRoute
  '/writing-coach': typeof ProtectedWritingCoachRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/word': typeof ApiWordRoute
  '/api/writing-coach': typeof ApiWritingCoachRoute
  '/w/$word': typeof WWordRoute
  '/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/vocabulary': typeof ProtectedVocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_immersive': typeof ImmersiveRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_immersive/warmup': typeof ImmersiveWarmupRoute
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/tr': typeof ProtectedTrRoute
  '/_protected/vocabulary': typeof ProtectedVocabularyRouteWithChildren
  '/_protected/writing-coach': typeof ProtectedWritingCoachRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/word': typeof ApiWordRoute
  '/api/writing-coach': typeof ApiWritingCoachRoute
  '/w/$word': typeof WWordRoute
  '/_protected/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/_protected/vocabulary/': typeof ProtectedVocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/warmup'
    | '/api-keys'
    | '/tr'
    | '/vocabulary'
    | '/writing-coach'
    | '/api/sentence'
    | '/api/word'
    | '/api/writing-coach'
    | '/w/$word'
    | '/vocabulary/import'
    | '/audio/w/$word'
    | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/warmup'
    | '/api-keys'
    | '/tr'
    | '/writing-coach'
    | '/api/sentence'
    | '/api/word'
    | '/api/writing-coach'
    | '/w/$word'
    | '/vocabulary/import'
    | '/audio/w/$word'
    | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/_immersive'
    | '/_protected'
    | '/_immersive/warmup'
    | '/_protected/api-keys'
    | '/_protected/tr'
    | '/_protected/vocabulary'
    | '/_protected/writing-coach'
    | '/api/sentence'
    | '/api/word'
    | '/api/writing-coach'
    | '/w/$word'
    | '/_protected/vocabulary/import'
    | '/audio/w/$word'
    | '/_protected/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImmersiveRoute: typeof ImmersiveRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiSentenceRoute: typeof ApiSentenceRoute
  ApiWordRoute: typeof ApiWordRoute
  ApiWritingCoachRoute: typeof ApiWritingCoachRoute
  WWordRoute: typeof WWordRoute
  AudioWWordRoute: typeof AudioWWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_immersive': {
      id: '/_immersive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ImmersiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$word': {
      id: '/w/$word'
      path: '/w/$word'
      fullPath: '/w/$word'
      preLoaderRoute: typeof WWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/writing-coach': {
      id: '/api/writing-coach'
      path: '/api/writing-coach'
      fullPath: '/api/writing-coach'
      preLoaderRoute: typeof ApiWritingCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/word': {
      id: '/api/word'
      path: '/api/word'
      fullPath: '/api/word'
      preLoaderRoute: typeof ApiWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentence': {
      id: '/api/sentence'
      path: '/api/sentence'
      fullPath: '/api/sentence'
      preLoaderRoute: typeof ApiSentenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/writing-coach': {
      id: '/_protected/writing-coach'
      path: '/writing-coach'
      fullPath: '/writing-coach'
      preLoaderRoute: typeof ProtectedWritingCoachRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vocabulary': {
      id: '/_protected/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof ProtectedVocabularyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tr': {
      id: '/_protected/tr'
      path: '/tr'
      fullPath: '/tr'
      preLoaderRoute: typeof ProtectedTrRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_immersive/warmup': {
      id: '/_immersive/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof ImmersiveWarmupRouteImport
      parentRoute: typeof ImmersiveRoute
    }
    '/_protected/vocabulary/': {
      id: '/_protected/vocabulary/'
      path: '/'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof ProtectedVocabularyIndexRouteImport
      parentRoute: typeof ProtectedVocabularyRoute
    }
    '/audio/w/$word': {
      id: '/audio/w/$word'
      path: '/audio/w/$word'
      fullPath: '/audio/w/$word'
      preLoaderRoute: typeof AudioWWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/vocabulary/import': {
      id: '/_protected/vocabulary/import'
      path: '/import'
      fullPath: '/vocabulary/import'
      preLoaderRoute: typeof ProtectedVocabularyImportRouteImport
      parentRoute: typeof ProtectedVocabularyRoute
    }
  }
}

interface ImmersiveRouteChildren {
  ImmersiveWarmupRoute: typeof ImmersiveWarmupRoute
}

const ImmersiveRouteChildren: ImmersiveRouteChildren = {
  ImmersiveWarmupRoute: ImmersiveWarmupRoute,
}

const ImmersiveRouteWithChildren = ImmersiveRoute._addFileChildren(
  ImmersiveRouteChildren,
)

interface ProtectedVocabularyRouteChildren {
  ProtectedVocabularyImportRoute: typeof ProtectedVocabularyImportRoute
  ProtectedVocabularyIndexRoute: typeof ProtectedVocabularyIndexRoute
}

const ProtectedVocabularyRouteChildren: ProtectedVocabularyRouteChildren = {
  ProtectedVocabularyImportRoute: ProtectedVocabularyImportRoute,
  ProtectedVocabularyIndexRoute: ProtectedVocabularyIndexRoute,
}

const ProtectedVocabularyRouteWithChildren =
  ProtectedVocabularyRoute._addFileChildren(ProtectedVocabularyRouteChildren)

interface ProtectedRouteChildren {
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedTrRoute: typeof ProtectedTrRoute
  ProtectedVocabularyRoute: typeof ProtectedVocabularyRouteWithChildren
  ProtectedWritingCoachRoute: typeof ProtectedWritingCoachRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedTrRoute: ProtectedTrRoute,
  ProtectedVocabularyRoute: ProtectedVocabularyRouteWithChildren,
  ProtectedWritingCoachRoute: ProtectedWritingCoachRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImmersiveRoute: ImmersiveRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiSentenceRoute: ApiSentenceRoute,
  ApiWordRoute: ApiWordRoute,
  ApiWritingCoachRoute: ApiWritingCoachRoute,
  WWordRoute: WWordRoute,
  AudioWWordRoute: AudioWWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
