/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWordRouteImport } from './routes/w.$word'
import { Route as ApiWordRouteImport } from './routes/api.word'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiSentenceRouteImport } from './routes/api.sentence'
import { Route as ProtectedVocabularyRouteImport } from './routes/_protected.vocabulary'
import { Route as ProtectedTrRouteImport } from './routes/_protected.tr'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWordRoute = WWordRouteImport.update({
  id: '/w/$word',
  path: '/w/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordRoute = ApiWordRouteImport.update({
  id: '/api/word',
  path: '/api/word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentenceRoute = ApiSentenceRouteImport.update({
  id: '/api/sentence',
  path: '/api/sentence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedVocabularyRoute = ProtectedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTrRoute = ProtectedTrRouteImport.update({
  id: '/tr',
  path: '/tr',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tr': typeof ProtectedTrRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/word': typeof ApiWordRoute
  '/w/$word': typeof WWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tr': typeof ProtectedTrRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/word': typeof ApiWordRoute
  '/w/$word': typeof WWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/tr': typeof ProtectedTrRoute
  '/_protected/vocabulary': typeof ProtectedVocabularyRoute
  '/api/sentence': typeof ApiSentenceRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/word': typeof ApiWordRoute
  '/w/$word': typeof WWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tr'
    | '/vocabulary'
    | '/api/sentence'
    | '/api/tts'
    | '/api/word'
    | '/w/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tr'
    | '/vocabulary'
    | '/api/sentence'
    | '/api/tts'
    | '/api/word'
    | '/w/$word'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/tr'
    | '/_protected/vocabulary'
    | '/api/sentence'
    | '/api/tts'
    | '/api/word'
    | '/w/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiSentenceRoute: typeof ApiSentenceRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWordRoute: typeof ApiWordRoute
  WWordRoute: typeof WWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$word': {
      id: '/w/$word'
      path: '/w/$word'
      fullPath: '/w/$word'
      preLoaderRoute: typeof WWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/word': {
      id: '/api/word'
      path: '/api/word'
      fullPath: '/api/word'
      preLoaderRoute: typeof ApiWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentence': {
      id: '/api/sentence'
      path: '/api/sentence'
      fullPath: '/api/sentence'
      preLoaderRoute: typeof ApiSentenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/vocabulary': {
      id: '/_protected/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof ProtectedVocabularyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tr': {
      id: '/_protected/tr'
      path: '/tr'
      fullPath: '/tr'
      preLoaderRoute: typeof ProtectedTrRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedTrRoute: typeof ProtectedTrRoute
  ProtectedVocabularyRoute: typeof ProtectedVocabularyRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTrRoute: ProtectedTrRoute,
  ProtectedVocabularyRoute: ProtectedVocabularyRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiSentenceRoute: ApiSentenceRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWordRoute: ApiWordRoute,
  WWordRoute: WWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
