/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ImmersiveRouteImport } from './routes/_immersive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWordRouteImport } from './routes/w.$word'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ProtectedWritingCoachRouteImport } from './routes/_protected.writing-coach'
import { Route as ProtectedVocabularyRouteImport } from './routes/_protected.vocabulary'
import { Route as ProtectedTrRouteImport } from './routes/_protected.tr'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected.api-keys'
import { Route as ImmersiveWarmupRouteImport } from './routes/_immersive.warmup'
import { Route as ProtectedWritingCoachIndexRouteImport } from './routes/_protected.writing-coach.index'
import { Route as ProtectedVocabularyIndexRouteImport } from './routes/_protected.vocabulary.index'
import { Route as AudioWWordRouteImport } from './routes/audio.w.$word'
import { Route as AudioPPhraseRouteImport } from './routes/audio.p.$phrase'
import { Route as ProtectedWritingCoachHistoryRouteImport } from './routes/_protected.writing-coach.history'
import { Route as ProtectedVocabularyImportRouteImport } from './routes/_protected.vocabulary.import'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersiveRoute = ImmersiveRouteImport.update({
  id: '/_immersive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWordRoute = WWordRouteImport.update({
  id: '/w/$word',
  path: '/w/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWritingCoachRoute = ProtectedWritingCoachRouteImport.update({
  id: '/writing-coach',
  path: '/writing-coach',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVocabularyRoute = ProtectedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTrRoute = ProtectedTrRouteImport.update({
  id: '/tr',
  path: '/tr',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ImmersiveWarmupRoute = ImmersiveWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => ImmersiveRoute,
} as any)
const ProtectedWritingCoachIndexRoute =
  ProtectedWritingCoachIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWritingCoachRoute,
  } as any)
const ProtectedVocabularyIndexRoute =
  ProtectedVocabularyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedVocabularyRoute,
  } as any)
const AudioWWordRoute = AudioWWordRouteImport.update({
  id: '/audio/w/$word',
  path: '/audio/w/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioPPhraseRoute = AudioPPhraseRouteImport.update({
  id: '/audio/p/$phrase',
  path: '/audio/p/$phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWritingCoachHistoryRoute =
  ProtectedWritingCoachHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedWritingCoachRoute,
  } as any)
const ProtectedVocabularyImportRoute =
  ProtectedVocabularyImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ProtectedVocabularyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/warmup': typeof ImmersiveWarmupRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/tr': typeof ProtectedTrRoute
  '/vocabulary': typeof ProtectedVocabularyRouteWithChildren
  '/writing-coach': typeof ProtectedWritingCoachRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/w/$word': typeof WWordRoute
  '/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/writing-coach/history': typeof ProtectedWritingCoachHistoryRoute
  '/audio/p/$phrase': typeof AudioPPhraseRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/vocabulary/': typeof ProtectedVocabularyIndexRoute
  '/writing-coach/': typeof ProtectedWritingCoachIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/warmup': typeof ImmersiveWarmupRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/tr': typeof ProtectedTrRoute
  '/api/$': typeof ApiSplatRoute
  '/w/$word': typeof WWordRoute
  '/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/writing-coach/history': typeof ProtectedWritingCoachHistoryRoute
  '/audio/p/$phrase': typeof AudioPPhraseRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/vocabulary': typeof ProtectedVocabularyIndexRoute
  '/writing-coach': typeof ProtectedWritingCoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_immersive': typeof ImmersiveRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_immersive/warmup': typeof ImmersiveWarmupRoute
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/tr': typeof ProtectedTrRoute
  '/_protected/vocabulary': typeof ProtectedVocabularyRouteWithChildren
  '/_protected/writing-coach': typeof ProtectedWritingCoachRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/w/$word': typeof WWordRoute
  '/_protected/vocabulary/import': typeof ProtectedVocabularyImportRoute
  '/_protected/writing-coach/history': typeof ProtectedWritingCoachHistoryRoute
  '/audio/p/$phrase': typeof AudioPPhraseRoute
  '/audio/w/$word': typeof AudioWWordRoute
  '/_protected/vocabulary/': typeof ProtectedVocabularyIndexRoute
  '/_protected/writing-coach/': typeof ProtectedWritingCoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/warmup'
    | '/api-keys'
    | '/tr'
    | '/vocabulary'
    | '/writing-coach'
    | '/api/$'
    | '/w/$word'
    | '/vocabulary/import'
    | '/writing-coach/history'
    | '/audio/p/$phrase'
    | '/audio/w/$word'
    | '/vocabulary/'
    | '/writing-coach/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/warmup'
    | '/api-keys'
    | '/tr'
    | '/api/$'
    | '/w/$word'
    | '/vocabulary/import'
    | '/writing-coach/history'
    | '/audio/p/$phrase'
    | '/audio/w/$word'
    | '/vocabulary'
    | '/writing-coach'
  id:
    | '__root__'
    | '/'
    | '/_immersive'
    | '/_protected'
    | '/_immersive/warmup'
    | '/_protected/api-keys'
    | '/_protected/tr'
    | '/_protected/vocabulary'
    | '/_protected/writing-coach'
    | '/api/$'
    | '/w/$word'
    | '/_protected/vocabulary/import'
    | '/_protected/writing-coach/history'
    | '/audio/p/$phrase'
    | '/audio/w/$word'
    | '/_protected/vocabulary/'
    | '/_protected/writing-coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImmersiveRoute: typeof ImmersiveRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  WWordRoute: typeof WWordRoute
  AudioPPhraseRoute: typeof AudioPPhraseRoute
  AudioWWordRoute: typeof AudioWWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_immersive': {
      id: '/_immersive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ImmersiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$word': {
      id: '/w/$word'
      path: '/w/$word'
      fullPath: '/w/$word'
      preLoaderRoute: typeof WWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/writing-coach': {
      id: '/_protected/writing-coach'
      path: '/writing-coach'
      fullPath: '/writing-coach'
      preLoaderRoute: typeof ProtectedWritingCoachRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vocabulary': {
      id: '/_protected/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof ProtectedVocabularyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tr': {
      id: '/_protected/tr'
      path: '/tr'
      fullPath: '/tr'
      preLoaderRoute: typeof ProtectedTrRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_immersive/warmup': {
      id: '/_immersive/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof ImmersiveWarmupRouteImport
      parentRoute: typeof ImmersiveRoute
    }
    '/_protected/writing-coach/': {
      id: '/_protected/writing-coach/'
      path: '/'
      fullPath: '/writing-coach/'
      preLoaderRoute: typeof ProtectedWritingCoachIndexRouteImport
      parentRoute: typeof ProtectedWritingCoachRoute
    }
    '/_protected/vocabulary/': {
      id: '/_protected/vocabulary/'
      path: '/'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof ProtectedVocabularyIndexRouteImport
      parentRoute: typeof ProtectedVocabularyRoute
    }
    '/audio/w/$word': {
      id: '/audio/w/$word'
      path: '/audio/w/$word'
      fullPath: '/audio/w/$word'
      preLoaderRoute: typeof AudioWWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/p/$phrase': {
      id: '/audio/p/$phrase'
      path: '/audio/p/$phrase'
      fullPath: '/audio/p/$phrase'
      preLoaderRoute: typeof AudioPPhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/writing-coach/history': {
      id: '/_protected/writing-coach/history'
      path: '/history'
      fullPath: '/writing-coach/history'
      preLoaderRoute: typeof ProtectedWritingCoachHistoryRouteImport
      parentRoute: typeof ProtectedWritingCoachRoute
    }
    '/_protected/vocabulary/import': {
      id: '/_protected/vocabulary/import'
      path: '/import'
      fullPath: '/vocabulary/import'
      preLoaderRoute: typeof ProtectedVocabularyImportRouteImport
      parentRoute: typeof ProtectedVocabularyRoute
    }
  }
}

interface ImmersiveRouteChildren {
  ImmersiveWarmupRoute: typeof ImmersiveWarmupRoute
}

const ImmersiveRouteChildren: ImmersiveRouteChildren = {
  ImmersiveWarmupRoute: ImmersiveWarmupRoute,
}

const ImmersiveRouteWithChildren = ImmersiveRoute._addFileChildren(
  ImmersiveRouteChildren,
)

interface ProtectedVocabularyRouteChildren {
  ProtectedVocabularyImportRoute: typeof ProtectedVocabularyImportRoute
  ProtectedVocabularyIndexRoute: typeof ProtectedVocabularyIndexRoute
}

const ProtectedVocabularyRouteChildren: ProtectedVocabularyRouteChildren = {
  ProtectedVocabularyImportRoute: ProtectedVocabularyImportRoute,
  ProtectedVocabularyIndexRoute: ProtectedVocabularyIndexRoute,
}

const ProtectedVocabularyRouteWithChildren =
  ProtectedVocabularyRoute._addFileChildren(ProtectedVocabularyRouteChildren)

interface ProtectedWritingCoachRouteChildren {
  ProtectedWritingCoachHistoryRoute: typeof ProtectedWritingCoachHistoryRoute
  ProtectedWritingCoachIndexRoute: typeof ProtectedWritingCoachIndexRoute
}

const ProtectedWritingCoachRouteChildren: ProtectedWritingCoachRouteChildren = {
  ProtectedWritingCoachHistoryRoute: ProtectedWritingCoachHistoryRoute,
  ProtectedWritingCoachIndexRoute: ProtectedWritingCoachIndexRoute,
}

const ProtectedWritingCoachRouteWithChildren =
  ProtectedWritingCoachRoute._addFileChildren(
    ProtectedWritingCoachRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedTrRoute: typeof ProtectedTrRoute
  ProtectedVocabularyRoute: typeof ProtectedVocabularyRouteWithChildren
  ProtectedWritingCoachRoute: typeof ProtectedWritingCoachRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedTrRoute: ProtectedTrRoute,
  ProtectedVocabularyRoute: ProtectedVocabularyRouteWithChildren,
  ProtectedWritingCoachRoute: ProtectedWritingCoachRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImmersiveRoute: ImmersiveRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  WWordRoute: WWordRoute,
  AudioPPhraseRoute: AudioPPhraseRoute,
  AudioWWordRoute: AudioWWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
